package oss.fosslight.common;

public enum SearchType {
    OSS("OSS"),
    PROJECT("PROJECT"),
    LICENSE("LICENSE"),
    SELF_CHECK("SELF_CHECK"),
    THIRD_PARTY("THIRD_PARTY"),
    VULNERABILITY("VULNERABILITY"),
    IDENTIFICATION_3RD("IDENTIFICATION_3RD"),
    IDENTIFICATION_DEP("IDENTIFICATION_DEP"),
    IDENTIFICATION_SRC("IDENTIFICATION_SRC"),
    IDENTIFICATION_BIN("IDENTIFICATION_BIN"),
    IDENTIFICATION_BOM("IDENTIFICATION_BOM"),
    IDENTIFICATION_ANDROID("IDENTIFICATION_ANDROID"),
    IDENTIFICATION_ANDROID_BOM("IDENTIFICATION_ANDROID_BOM"),
	SECURITY_NEED("SECURITY_NEED"),
	SECURITY_FULL("SECURITY_FULL"),
	IDENTIFICATION_PARTNER("IDENTIFICATION_PARTNER"),
	IDENTIFICATION_PARTNER_BOM("IDENTIFICATION_PARTNER_BOM"),
	IDENTIFICATION_SELF_CHECK("IDENTIFICATION_SELF_CHECK");

    private final String name;

    SearchType(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
