# Copyright (c) Sameer1046
# SPDX-License-Identifier: AGPL-3.0-only

version: "3.5"
services:
  db:
    image: mariadb:10
    container_name: fosslight_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: docker.env
    environment:
      TZ: Asia/Seoul
    restart: always
    expose:
      - "3306"
  web:
    build: .
    container_name: fosslight_web
    depends_on:
      - db
    ports:
      - "8180:8180"
    volumes:
      - ./web-data:/data/fosslight
    environment:
      TZ: Asia/Seoul
    command: sh -c "./wait-for db:3306 -t 120 && java -jar FOSSLight.war --root.dir=${ROOT_DIR:-/data/fosslight}
      --server.port=${SERVICE_PORT:-8180}
      --spring.datasource.url=${DATABASE_SOURCE:-db:3306/fosslight}
      --spring.datasource.username=${DATABASE_USER:-fosslight}
      --spring.datasource.password=${DATABASE_PASSWORD:-fosslight}
      --logging.path=${LOGGING_PATH:-/data/fosslight/logs}
      --verify.bin.path=./verify
      --export.template.path=./template"
  mail:
    image: mailserver/docker-mailserver:10
    container_name: fosslight_mail
    hostname: mail
    domainname: fosslight.org
    ports:
      - "25:25"
      - "587:587"
    expose:
      - "25"
      - "587"
    volumes:
      - ./mail/maildata/:/var/mail
      - ./mail/mailstate/:/var/mail-state
      - ./mail/maillogs/:/var/log/mail
      - ./mail/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
