-- Change Default Tab Name
UPDATE T2_CODE_DTL SET CD_DTL_NM='License' WHERE CD_NO=701 AND CD_DTL_NO=002;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Open Source' WHERE CD_NO=701 AND CD_DTL_NO=003;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Project' WHERE CD_NO=701 AND CD_DTL_NO=004;
UPDATE T2_CODE_DTL SET CD_DTL_NM='3rd Party' WHERE CD_NO=701 AND CD_DTL_NO=005;
UPDATE T2_CODE_DTL SET CD_DTL_NM='BAT' WHERE CD_NO=701 AND CD_DTL_NO=006;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Binary DB' WHERE CD_NO=701 AND CD_DTL_NO=007;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Vulnerability' WHERE CD_NO=701 AND CD_DTL_NO=008;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Self-check' WHERE CD_NO=701 AND CD_DTL_NO=009;