-- // update_v2.1.1
-- Migration SQL that makes the change goes here.

ALTER TABLE `OSS_DOWNLOADLOCATION` DROP FULLTEXT INDEX `DOWNLOAD_LOCATION` (DOWNLOAD_LOCATION);
ALTER TABLE `OSS_DOWNLOADLOCATION` ADD INDEX `DOWNLOAD_LOCATION` (DOWNLOAD_LOCATION);

