-- Change Default Tab Name
UPDATE T2_CODE_DTL SET CD_DTL_NM='License' WHERE CD_NO=701 AND CD_DTL_NO=002;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Open Source' WHERE CD_NO=701 AND CD_DTL_NO=003;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Project' WHERE CD_NO=701 AND CD_DTL_NO=004;
UPDATE T2_CODE_DTL SET CD_DTL_NM='3rd Party' WHERE CD_NO=701 AND CD_DTL_NO=005;
UPDATE T2_CODE_DTL SET CD_DTL_NM='BAT' WHERE CD_NO=701 AND CD_DTL_NO=006;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Binary DB' WHERE CD_NO=701 AND CD_DTL_NO=007;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Vulnerability' WHERE CD_NO=701 AND CD_DTL_NO=008;
UPDATE T2_CODE_DTL SET CD_DTL_NM='Self-check' WHERE CD_NO=701 AND CD_DTL_NO=009;

-- Change Comment division
UPDATE T2_CODE_DTL SET CD_DTL_NM='ProjectInfo' WHERE CD_NO=214 AND CD_DTL_NO=19;

-- Change BOM oss info
UPDATE T2_CODE_DTL SET CD_DTL_EXP='SELECT T1.*, GROUP_CONCAT(DISTINCT(T2.LICENSE_NAME)) AS LICENSE_NAME FROM OSS_COMPONENTS T1 INNER JOIN OSS_COMPONENTS_LICENSE T2 ON T1.COMPONENT_ID = T2.COMPONENT_ID AND IFNULL(T2.EXCLUDE_YN, \'N\') = \'N\' WHERE REFERENCE_ID = ? AND REFERENCE_DIV = \'13\' AND T1.MERGE_PRE_DIV IS NULL GROUP BY T1.OSS_NAME, T1.OSS_VERSION ORDER BY COMPONENT_ID' WHERE CD_NO = 104 AND CD_DTL_NO = 201;

ALTER TABLE `PROJECT_MASTER` ADD `PACKAGE_FILE_TYPE1` varchar(1) NULL DEFAULT NULL;
ALTER TABLE `PROJECT_MASTER` ADD `PACKAGE_FILE_TYPE2` varchar(1) NULL DEFAULT NULL;
ALTER TABLE `PROJECT_MASTER` ADD `PACKAGE_FILE_TYPE3` varchar(1) NULL DEFAULT NULL;