ALTER TABLE `OSS_COMPONENTS_LICENSE` DROP CONSTRAINT `fk_OSS_COMPONENTS_LICENSE_OSS_COMPONENTS1`;

INSERT INTO
    `T2_CODE_DTL` (
    `CD_NO`,
    `CD_DTL_NO`,
    `CD_DTL_NM`,
    `CD_SUB_NO`,
    `CD_DTL_EXP`,
    `CD_ORDER`,
    `USE_YN`
)
VALUES
    ('205', 'FREV', 'Final Review', '', '', 6, 'Y'),
    ('206', 'FREV', 'Final Review', '', 'Final Review', 6, 'Y');
    
ALTER TABLE `PROJECT_MASTER`
    ADD `PACKAGE_FILE_ID4` int(11) DEFAULT NULL,
    ADD `PACKAGE_FILE_TYPE4` varchar(1) DEFAULT NULL,
    ADD `OSDD_SOURCE_FILE_NAME4` varchar(512) DEFAULT 'N',
    ADD `OSDD_SOURCE_FILE_ETAG4` varchar(512) DEFAULT 'N';
    
UPDATE T2_CODE_DTL SET CD_DTL_EXP='SELECT T1.DISTRIBUTE_NAME, T1.DISTRIBUTE_MASTER_CATEGORY, T1.DISTRIBUTE_SOFTWARE_TYPE, T1.DISTRIBUTE_DEPLOY_TIME, T1.DISTRIBUTE_DEPLOY_YN, T1.DISTRIBUTE_DEPLOY_MODEL_YN, T1.DISTRIBUTE_DEPLOY_ERROR_MSG, T1.DISTRIBUTE_TARGET, (SELECT A1.ORIG_NM FROM T2_FILE A1 WHERE A1.FILE_SEQ = T1.PACKAGE_FILE_ID) AS PACKAGE_FILE_ID, (SELECT A1.ORIG_NM FROM T2_FILE A1 WHERE A1.FILE_SEQ = T1.PACKAGE_FILE_ID2) AS PACKAGE_FILE_ID2, (SELECT A1.ORIG_NM FROM T2_FILE A1WHERE A1.FILE_SEQ = T1.PACKAGE_FILE_ID3) AS PACKAGE_FILE_ID3, (SELECT A1.ORIG_NM FROM T2_FILE A1 WHERE A1.FILE_SEQ = T1.PACKAGE_FILE_ID4) AS PACKAGE_FILE_ID4, (SELECT A1.ORIG_NM FROM T2_FILE A1 WHERE A1.FILE_SEQ = T1.NOTICE_FILE_ID) AS NOTICE_FILE_ID FROM PROJECT_MASTER T1 WHERE T1.PRJ_ID = ?' WHERE CD_NO=104 AND CD_DTL_NO=203;

ALTER TABLE `PROJECT_MASTER` ADD `SCRT_CSV_FILE_ID` int(11) DEFAULT NULL;