-- // update_v2.5.0
-- Migration SQL that makes the change goes here.

UPDATE `T2_CODE_DTL` SET CD_DTL_EXP = 'SELECT  T3.OSS_ID , T1.OSS_NAME , T1.OSS_VERSION , CONCAT(T3.CVE_ID, \' -> \' , IF(T3.CVE_ID_TO = \'\' OR T3.CVE_ID_TO IS NULL, \'NONE\', T3.CVE_ID_TO)) AS CVE_ID , CONCAT(CAST(T3.CVSS_SCORE AS DECIMAL(10, 1)), \' -> \' , CAST(T3.CVSS_SCORE_TO AS DECIMAL(10, 1))) AS CVSS_SCORE , T2.VULN_SUMMARY , DATE_FORMAT(T2.MODI_DATE, \'%Y-%m-%d\') AS MODI_DATE , DATE_FORMAT(T2.PUBL_DATE, \'%Y-%m-%d\') AS PUBL_DATE FROM OSS_MASTER T1  LEFT JOIN NVD_CVE_V3 T2 ON T1.CVE_ID = T2.CVE_ID  INNER JOIN NVD_OSS_HIS T3 ON T1.OSS_ID = T3.OSS_ID AND T3.REG_DT > ADDDATE(SYSDATE(), INTERVAL - 1 DAY) AND CAST(T3.CVSS_SCORE AS DECIMAL(10, 1)) > CAST(T3.CVSS_SCORE_TO AS DECIMAL(10, 1)) AND T3.CVSS_SCORE_TO != \'10.0\' AND CAST(T3.CVSS_SCORE AS DECIMAL(10, 1)) >= 7.0 AND CAST(T3.CVSS_SCORE_TO AS DECIMAL(10, 1)) < 7.0 GROUP BY OSS_ID, CVE_ID ORDER BY OSS_NAME, OSS_VERSION, CVSS_SCORE DESC' WHERE CD_NO = '104' AND CD_DTL_NO = '212';

-- //@UNDO
-- SQL to undo the change goes here.


