INSERT INTO `T2_CODE_DTL` (`CD_NO`, `CD_DTL_NO`, `CD_DTL_NM`, `CD_SUB_NO`, `CD_DTL_EXP`, `CD_ORDER`, `USE_YN`) VALUES ('903', '014', 'pkg.go.dev', '', 'go url', 14, 'Y');

INSERT INTO `T2_CODE_DTL` (`CD_NO`, `CD_DTL_NO`, `CD_DTL_NM`, `CD_SUB_NO`, `CD_DTL_EXP`, `CD_ORDER`, `USE_YN`) VALUES ('111', '460', 'Project Identification Confirmed Network Service Only', '', '<p>Network상의 이용을 배포로 간주하는 License (ex- AGPL-3.0)가 사용되지 않았음을 확인했으며, OSC Process 완료되었습니다.<br />The OSC Process is completed because the Network Copyleft License (ex- AGPL-3.0) is not used.</p>', 460, 'Y');

ALTER TABLE `PROJECT_MASTER` ADD `PACKAGE_FILE_ID5` int(11) DEFAULT NULL, ADD `PACKAGE_FILE_TYPE5` varchar(1) DEFAULT NULL, ADD `OSDD_SOURCE_FILE_NAME5` varchar(512) DEFAULT 'N', ADD `OSDD_SOURCE_FILE_ETAG5` varchar(512) DEFAULT 'N';

ALTER TABLE `LICENSE_MASTER` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);
ALTER TABLE `LICENSE_NICKNAME` CHANGE `LICENSE_NICKNAME` `LICENSE_NICKNAME` VARCHAR(600);
ALTER TABLE `OSS_COMPONENTS_LICENSE` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);
ALTER TABLE `PRE_OSS_COMPONENTS_LICENSE` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);

ALTER TABLE `PROJECT_MASTER` DROP COLUMN `PACKAGE_VUL_DOC_FILE_ID`;
ALTER TABLE `PROJECT_MASTER` DROP COLUMN `VUL_DOC_SKIP_YN`;

UPDATE `T2_CODE_DTL` SET CD_DTL_EXP = 'SELECT T.* FROM ( SELECT T1.COMPONENT_ID, T1.REF_COMPONENT_ID, T1.REFERENCE_ID, T1.OSS_NAME, T1.OSS_VERSION, T1.DOWNLOAD_LOCATION, T1.HOMEPAGE, GROUP_CONCAT(T3.LICENSE_NAME ORDER BY T3.LICENSE_ID DESC SEPARATOR \',\') AS LICENSE_NAME FROM ( SELECT A1.* FROM OSS_COMPONENTS A1 INNER JOIN OSS_MASTER A3  ON A1.OSS_NAME = A3.OSS_NAME AND A1.OSS_VERSION = A3.OSS_VERSION AND A3.USE_YN = \'Y\' WHERE REFERENCE_ID = ? AND REFERENCE_DIV = (SELECT CASE WHEN NOTICE_TYPE = \'80\' THEN \'17\' ELSE \'13\' END REFERENCE_DIV FROM OSS_NOTICE WHERE PRJ_ID = ?) AND MERGE_PRE_DIV IS NULL  AND A1.OBLIGATION_TYPE = \'11\' ) T1 INNER JOIN OSS_COMPONENTS T2 ON T1.REF_COMPONENT_ID = T2.COMPONENT_ID INNER JOIN OSS_COMPONENTS_LICENSE T3 ON T1.REF_COMPONENT_ID = T3.COMPONENT_ID GROUP BY T1.COMPONENT_ID) T' WHERE CD_NO = '104' AND CD_DTL_NO = '202';