INSERT INTO `T2_CODE_DTL` (`CD_NO`, `CD_DTL_NO`, `CD_DTL_NM`, `CD_SUB_NO`, `CD_DTL_EXP`, `CD_ORDER`, `USE_YN`) VALUES ('903', '014', 'pkg.go.dev', '', 'go url', 14, 'Y');

INSERT INTO `T2_CODE_DTL` (`CD_NO`, `CD_DTL_NO`, `CD_DTL_NM`, `CD_SUB_NO`, `CD_DTL_EXP`, `CD_ORDER`, `USE_YN`) VALUES ('111', '460', 'Project Identification Confirmed Network Service Only', '', '<p>Network상의 이용을 배포로 간주하는 License (ex- AGPL-3.0)가 사용되지 않았음을 확인했으며, OSC Process 완료되었습니다.<br />The OSC Process is completed because the Network Copyleft License (ex- AGPL-3.0) is not used.</p>', 460, 'Y');

ALTER TABLE `PROJECT_MASTER` ADD `PACKAGE_FILE_ID5` int(11) DEFAULT NULL, ADD `PACKAGE_FILE_TYPE5` varchar(1) DEFAULT NULL, ADD `OSDD_SOURCE_FILE_NAME5` varchar(512) DEFAULT 'N', ADD `OSDD_SOURCE_FILE_ETAG5` varchar(512) DEFAULT 'N';

ALTER TABLE `LICENSE_MASTER` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);
ALTER TABLE `LICENSE_NICKNAME` CHANGE `LICENSE_NICKNAME` `LICENSE_NICKNAME` VARCHAR(600);
ALTER TABLE `OSS_COMPONENTS_LICENSE` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);
ALTER TABLE `PRE_OSS_COMPONENTS_LICENSE` CHANGE `LICENSE_NAME` `LICENSE_NAME` VARCHAR(600);