-- // update_v2.5.0 (add NVD_DATA_V3 PRODUCTVERSION index)
-- Migration SQL that makes the change goes here.
-- Add PRODUCTVERSION index used by ProjectMapper FORCE INDEX (PRODUCTVERSION)
ALTER TABLE `NVD_DATA_V3`
  ADD KEY `PRODUCTVERSION` (`PRODUCT`, `VERSION`);

-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE `NVD_DATA_V3`
  DROP KEY `PRODUCTVERSION`;

-- SQL related to the coReviewer functionality
CREATE TABLE `ENT_ANALYSIS_JOB` (
	`JOB_SEQ` INT(11) NOT NULL AUTO_INCREMENT,
	`REFERENCE_ID` VARCHAR(50) NOT NULL COLLATE 'utf8mb4',
	`DIVISION` VARCHAR(50) NOT NULL COLLATE 'utf8mb4',
	`ANALYSIS_START_DATE` DATETIME NULL DEFAULT current_timestamp(),
	`ANALYSIS_END_DATE` DATETIME NULL DEFAULT current_timestamp(),
	`SUCCESS_COUNT` INT(11) NOT NULL DEFAULT '0',
	`FAILURE_COUNT` INT(11) NOT NULL DEFAULT '0',
	`TOTAL_COUNT` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`JOB_SEQ`) USING BTREE,
	INDEX `REFERENCE_ID` (`REFERENCE_ID`) USING BTREE,
	INDEX `DIVISION` (`DIVISION`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

-- SQL related to the OSV functionality
CREATE TABLE `OSV_VULNERABILITIES` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`OSV_ID` VARCHAR(50) NOT NULL COMMENT 'Unique OSV Identifier (e.g., CVE-2021-3114, GHSA-vp9c-fpxx-744v)' COLLATE 'utf8mb4',
	`SCHEMA_VERSION` VARCHAR(20) NULL DEFAULT NULL COMMENT 'OSV Schema Version' COLLATE 'utf8mb4',
	`SUMMARY` LONGTEXT NULL DEFAULT NULL COMMENT 'Short summary or title (under 120 characters)' COLLATE 'utf8mb4',
	`DETAILS` LONGTEXT NULL DEFAULT NULL COMMENT 'Detailed technical description of the vulnerability' COLLATE 'utf8mb4',
	`PUBL_DATE` DATETIME NULL DEFAULT NULL COMMENT 'Initial publication date',
	`MODI_DATE` DATETIME NULL DEFAULT NULL COMMENT 'Last modification date',
	`WITHDRAWN` DATETIME NULL DEFAULT NULL COMMENT 'Withdrawal date (If present, exclude from OSS matching filters)',
	`RAW_JSON` LONGTEXT NULL DEFAULT NULL COMMENT 'Full fallback JSON string containing references, credits, database_specific, etc.' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `OSV_ID` (`OSV_ID`) USING BTREE,
	INDEX `WITHDRAWN` (`WITHDRAWN`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_SEVERITIES` (
	`ID` INT(11) NOT NULL COMMENT 'Reference to OSV_VULNERABILITIES.ID',
	`PACKAGE_NAME` VARCHAR(255) NOT NULL COMMENT 'Affected package name' COLLATE 'utf8mb4',
	`ECOSYSTEM` VARCHAR(200) NOT NULL COMMENT 'Package ecosystem' COLLATE 'utf8mb4',
	`SOURCE` VARCHAR(50) NOT NULL COMMENT 'PACKAGE, GLOBAL, PACKAGE_DB, GLOBAL_DB, PACKAGE_ECO' COLLATE 'utf8mb4',
	`TYPE` VARCHAR(30) NOT NULL COMMENT 'Metrics system type (e.g., CVSS_V4, CVSS_V3, CVSS_V2, Ubuntu, Android)' COLLATE 'utf8mb4',
	`SCORE` LONGTEXT NOT NULL COMMENT 'Calculated numeric score string or raw text rating' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`, `PACKAGE_NAME`, `ECOSYSTEM`, `SOURCE`, `TYPE`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_ALIASES` (
	`ID` INT(11) NOT NULL COMMENT 'Reference to OSV_VULNERABILITIES.ID',
	`ALIAS_ID` VARCHAR(200) NOT NULL COMMENT 'Alternative identifier mapping (e.g., CVE, GHSA)' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`, `ALIAS_ID`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_REFERENCES` (
	`OSV_ID` VARCHAR(50) NOT NULL COMMENT 'OSV ID' COLLATE 'utf8mb4',
	`REF_IDX` INT(11) NOT NULL COMMENT 'Reference Index',
	`TYPE` VARCHAR(30) NULL DEFAULT NULL COMMENT 'Reference Type' COLLATE 'utf8mb4',
	`PATCH_LINK` VARCHAR(2000) NULL DEFAULT NULL COMMENT 'Reference URL' COLLATE 'utf8mb4',
	PRIMARY KEY (`OSV_ID`, `REF_IDX`) USING BTREE,
	INDEX `IDX_REF_TYPE` (`TYPE`) USING BTREE,
	INDEX `IDX_REF_OSV` (`OSV_ID`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_AFFECTED_PACKAGES` (
	`ID` INT(11) NOT NULL COMMENT 'Reference to OSV_VULNERABILITIES.ID',
	`PACKAGE_IDX` INT(11) NOT NULL,
	`ECOSYSTEM` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Package manager ecosystem (e.g., Maven, npm, PyPI)' COLLATE 'utf8mb4',
	`PACKAGE_NAME` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Name of the affected package/library' COLLATE 'utf8mb4',
	`PURL` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Package URL identifier string' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`, `PACKAGE_IDX`) USING BTREE,
	INDEX `IDX_PACKAGES` (`ECOSYSTEM`, `PACKAGE_NAME`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_AFFECTED_PACKAGES_VERSIONS` (
	`ID` INT(11) NOT NULL COMMENT 'Reference to OSV_VULNERABILITIES.ID',
	`PACKAGE_IDX` INT(11) NOT NULL,
	`VERSION_IDX` INT(11) NOT NULL,
	`VERSION` VARCHAR(255) NOT NULL COMMENT 'Concrete affected version string' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`, `PACKAGE_IDX`, `VERSION_IDX`) USING BTREE,
	INDEX `IDX_VERSIONS_PREF` (`ID`, `PACKAGE_IDX`, `VERSION_IDX`, `VERSION`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

CREATE TABLE `OSV_AFFECTED_PACKAGE_RANGES` (
	`ID` INT(11) NOT NULL COMMENT 'Reference to OSV_VULNERABILITIES.ID',
	`PACKAGE_IDX` INT(11) NOT NULL,
	`RANGE_IDX` INT(11) NOT NULL COMMENT 'Array element sequence index within the package definition',
	`RANGE_TYPE` VARCHAR(20) NOT NULL COMMENT 'Version comparison format (SEMVER, ECOSYSTEM, GIT)' COLLATE 'utf8mb4',
	`REPO` LONGTEXT NULL DEFAULT NULL COMMENT 'Git repository URL (Required for GIT type)' COLLATE 'utf8mb4',
	`INTRODUCED` VARCHAR(50) NULL DEFAULT '0' COMMENT 'Lower bound version (0 means from the beginning of time)' COLLATE 'utf8mb4',
	`FIXED` LONGTEXT NULL DEFAULT NULL COMMENT 'Upper bound version where the issue is resolved (Exclusive)' COLLATE 'utf8mb4',
	`LAST_AFFECTED` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Maximum affected version string (Inclusive)' COLLATE 'utf8mb4',
	`LIMIT_VERSION` VARCHAR(50) NULL DEFAULT '*' COMMENT 'Upper constraint boundary (* means infinity)' COLLATE 'utf8mb4',
	PRIMARY KEY (`ID`, `PACKAGE_IDX`, `RANGE_IDX`) USING BTREE,
	INDEX `RANGE_TYPE` (`RANGE_TYPE`) USING BTREE,
	INDEX `REPO` (`REPO`(768)) USING BTREE,
	INDEX `IDX_RANGES_PERF` (`ID`, `PACKAGE_IDX`, `RANGE_IDX`) USING BTREE
) COLLATE='utf8mb4' ENGINE=InnoDB;

ALTER TABLE OSS_COMPONENTS ADD JOB_SEQ INT(11) DEFAULT NULL;

ALTER TABLE OSS_DISCOVERED_SND_EMAIL MODIFY COLUMN CVE_ID VARCHAR(128);

ALTER TABLE NVD_DATA_SECURITY MODIFY COLUMN CVE_ID VARCHAR(128);