# SPDX-FileCopyrightText: Copyright 2021 LG Electronics Inc
# SPDX-License-Identifier: AGPL-3.0-only

name: Merged to develop branch

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_IP }}
          username: ${{ secrets.DEV_REMOTE_SSH_ID }}
          key: ${{ secrets.DEV_REMOTE_SSH_KEY }}
          port: ${{ secrets.DEV_REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/workspace/fosslight
            sudo docker-compose down
            git pull
            sudo docker-compose up --build -d
